### ISSUE TITLE
Add definitions in the model

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/ISO19111#19]
Add/update definitions in the UML model from the document.

**Comment by RogerLott** [comment]
[19111 UML descriptions 2017-05-30.xlsx](https://github.com/ISO-TC211/ISO19111/files/1068070/19111.UML.descriptions.2017-05-30.xlsx)
Definitions for classes and attributes from WD 2017-05-30 (post Stockholm) are in attached spreadsheet. Unchanged, changed and new are differentiated by colour.

**Comment by RogerLott** [comment]
[19111 UML descriptions 2017-06-14.xlsx](https://github.com/ISO-TC211/ISO19111/files/1075367/19111.UML.descriptions.2017-06-14.xlsx)
Additional definitions for the Axis direction attributes added from 19162 included in this version.

**Comment by RogerLott** [comment]
The spreadsheet I sent 10 minutes ago is ok for the additional AxisDirection attributes but does not address the changes made to the VerticalMethod or CoordinateMetadata classes agreed this afternoon. I will send an update.

**Comment by RogerLott** [comment]
[19111 UML descriptions 2017-09-30.xlsx](https://github.com/ISO-TC211/ISO19111/files/1348019/19111.UML.descriptions.2017-09-30.xlsx)
Updated descriptions for classes and attributes attached. These are (I hope) consistent with the outstanding model changes described in the powerpoint file attached.
[Amendments required at 2017-09-28.pptx](https://github.com/ISO-TC211/ISO19111/files/1348023/Amendments.required.at.2017-09-28.pptx)

**Comment by jetgeo** [comment]
Changes according to done. Definitions will be added. 
See new figures in https://github.com/ISO-TC211/ISO19111/tree/master/Figures

**Comment by desruisseaux** [comment]
Thanks for the updated figures. Just minor questions:

* In "Coordinate Reference Systems.png" and in "Datum CRS associations.png", the association between CRS and datum seems navigable in both directions. Is it intended? Do we mean that each datum should know all CRS that use them?
* Should we add the constraint that all `Datum` instances in an `Ensemble` shall be of the same type? E.g. an `Ensemble` shall not contain mix of `GeodeticReferenceFrame` and `VerticalReferenceFrame`?

**Comment by jetgeo** [comment]
> In "Coordinate Reference Systems.png" and in "Datum CRS associations.png", the association between CRS and datum seems navigable in both directions. Is it intended? Do we mean that each datum should know all CRS that use them?

The navigability was set to enable the Ellipsoid constraint on GeodeticReferenceFrame. This constraint is now moved to GeodeticCRS, so the navigability is no longer needed. 

> Should we add the constraint that all Datum instances in an Ensemble shall be of the same type? E.g. an Ensemble shall not contain mix of GeodeticReferenceFrame and VerticalReferenceFrame?

Someone else must answer this.

**Comment by RogerLott** [comment]
I saw the two-way relationship some time ago and wondered why it was there, but then forgot to ask about the issue. It was one way in 19111:2007 and except possibly for the contraint issue there is no need to change from that.  But I don't see any constraint on GeodeticCRS in the current versions of the diagrams. It seems to have gone missing from the CS-CRS association diagram.

So (i) show the constraint (coordinateSystem.oclAsType(EllipsoidalCS) implies count(datum.ellipsoid)=1) in the GeodeticCRS class in the CS-CRS associations diagram, (ii) make the DefingDatum associations one-directions from CRS to datum (also in inherited subtypes).

**Comment by jetgeo** [comment]
@RogerLott: Both (i) and (ii) is done (and was done before your comment :)). 
See https://github.com/ISO-TC211/ISO19111/blob/master/Figures/CS%20CRS%20Associations.png
And https://github.com/ISO-TC211/ISO19111/blob/master/Figures/Datum%20CRS%20Associations.png

**Comment by RogerLott** [comment]
Descriptions/definitions updated as in DIS draft of 2018-01-26 in attached spreadsheet. Those that are believed to have changed are in red, although it is possible that some others may also have done so. Once added to the HM I believe this issue may be closed.
[19111 UML descriptions DIS 2018-01-27.xlsx](https://github.com/ISO-TC211/ISO19111/files/1673115/19111.UML.descriptions.DIS.2018-01-27.xlsx)

**Comment by jetgeo** [comment]
I have updated the definitions in the Harmonized Model. However, we should also have definitions for all navigable roles. 
The attached spreadsheet contains all definitions from the model. The empty ones are the navigable roles that should have a definition. 
[19111.UML.descriptions.DIS.2018-012-06.xlsx](https://github.com/ISO-TC211/ISO19111/files/1698411/19111.UML.descriptions.DIS.2018-012-06.xlsx)

**Comment by RogerLott** [comment]
Attached is a spreadsheet containing definitions for all classes, associations and attributes in the 19111 model. Note that the definitions for the classes and for the attributes have all had minor modification, mainly to conform to ISO definition requirements through removal of the initial article and final full stop, but in some cases some minor changes to wording to improve clarity.
The definitions for the associations (in blue font) are all new to the 19111 document. In the attached spreadsheet, associations in italics are those that I believe to be non-navigable - please confirm that I have these correct. 
Associations highlighted in yellow are those that you (@jetgeo) flagged as missing (I am not sure how you have definitions for some you have not marked!). Please check them all, but in particular I would like your confirmation (or otherwise) on those association roles and definitions which I have highlighted with red background.
[19111 UML descriptions IS 2018-07-24.xlsx](https://github.com/ISO-TC211/ISO19111/files/2224185/19111.UML.descriptions.IS.2018-07-24.xlsx)

**Comment by RogerLott** [comment]
Just realised that in the descriptions for non-navigable associations the plurals are unnecessary as multiplicity is taken care of by the cardinality. Updated spreadsheet attached.

**Comment by RogerLott** [comment]
Just realised that in the descriptions for non-navigable associations the plurals are unnecessary as multiplicity is taken care of by the cardinality. Updated spreadsheet attached.
[19111 UML descriptions IS 2018-07-26.xlsx](https://github.com/ISO-TC211/ISO19111/files/2230856/19111.UML.descriptions.IS.2018-07-26.xlsx)

**Comment by RogerLott** [comment]
Just realised that in the descriptions for non-navigable associations the plurals are unnecessary as multiplicity is taken care of by the cardinality. Updated spreadsheet attached.
[19111 UML descriptions IS 2018-07-26.xlsx](https://github.com/ISO-TC211/ISO19111/files/2232833/19111.UML.descriptions.IS.2018-07-26.xlsx)

**Comment by RogerLott** [comment]
Attached is a spreadsheet containing definitions for all classes, associations and attributes in the 19111 model. Note that the definitions for the classes and for the attributes have all had minor modification, mainly to conform to ISO definition requirements through removal of the initial article and final full stop, but in some cases some minor changes to wording to improve clarity.
 The definitions for the associations (in blue font) are all new to the 19111 document. In the attached spreadsheet, associations in italics are those that I believe to be non-navigable - please confirm that I have these correct.
 Associations highlighted in yellow are those that you (@jetgeo) flagged as missing (I am not sure how you have definitions for some you have not marked!). Please check them all, but in particular I would like your confirmation (or otherwise) on those association roles and definitions which I have highlighted with red background.
[19111 UML descriptions IS 2018-07-26.xlsx](https://github.com/ISO-TC211/ISO19111/files/2232842/19111.UML.descriptions.IS.2018-07-26.xlsx)

**Comment by RogerLott** [comment]
[19111 UML descriptions IS 2018-08-08.xlsx](https://github.com/ISO-TC211/ISO19111/files/2272155/19111.UML.descriptions.IS.2018-08-08.xlsx)
Attached is spreadsheet containing the agreed final definitions for all classes, associations and attributes in the 19111 model. Non-navigable associations have been deleted from the 19111 document and the attached spreadsheet. Unless you notice some errors I believe that after these definitions have been loaded to the HM this issue may be closed.

**Comment by jetgeo** [comment]
Done. No missing definitions in the model now.
